on: [push]

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    name: Run unit tests
    steps:  
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run lint
      - run: npm run test
