on: [push]

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    name: Run unit tests
    steps:  
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm test

  test-action:
    runs-on: ubuntu-latest
    name: Test action
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          source: commit
